sudo: required 
services:
  - docker

before_install:
  - docker build -t sumeetpri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sumeetpri/react-test npm test -- --coverage

after_success:
  - docker build -t sumeetpri/multi-client ./client
  - docker build -t sumeetpri/multi-nginx ./nginx
  - docker build -t sumeetpri/multi-server ./server
  - docker build -t sumeetpri/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sumeetpri/multi-client
  - docker push sumeetpri/multi-nginx
  - docker push sumeetpri/multi-server
  - docker push sumeetpri/multi-worker
